"""changed updated & created for git_repositories

Revision ID: 22cb80d2b356
Revises: 828215855bd1
Create Date: 2026-03-05 04:53:09.986846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22cb80d2b356'
down_revision: Union[str, Sequence[str], None] = '828215855bd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('git_repositories', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('git_repositories', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('git_repositories', 'updated_at')
    op.drop_column('git_repositories', 'created_at')
    # ### end Alembic commands ###
