"""changing table names and model names for less confusion AppRecord to GitApp and InstallationRecord to GitInstall, changed table names to git_apps & git_installs

Revision ID: 5c49e712406e
Revises: c9944d09f49c
Create Date: 2025-10-28 01:07:54.374897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c49e712406e'
down_revision: Union[str, Sequence[str], None] = 'c9944d09f49c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_github_installation_records_id'), table_name='github_installation_records')
    op.drop_table('github_installation_records')
    op.drop_index(op.f('ix_github_app_records_id'), table_name='github_app_records')
    op.drop_table('github_app_records')
    op.add_column('users', sa.Column('git_id', sa.Integer(), nullable=False))
    op.drop_column('users', 'github_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'git_id')
    op.create_table('github_app_records',
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('node_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('external_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('html_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('github_app_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expires_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('github_app_records_pkey'))
    )
    op.create_index(op.f('ix_github_app_records_id'), 'github_app_records', ['id'], unique=False)
    op.create_table('github_installation_records',
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('app_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('app_slug', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('access_tokens_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('html_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('repositories_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('installation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('github_installation_records_pkey'))
    )
    op.create_index(op.f('ix_github_installation_records_id'), 'github_installation_records', ['id'], unique=False)
    # ### end Alembic commands ###
