"""requiring app_id app_slug in git_installs

Revision ID: 62c14a84d5fa
Revises: 5c49e712406e
Create Date: 2025-10-28 22:13:05.111871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c14a84d5fa'
down_revision: Union[str, Sequence[str], None] = '5c49e712406e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('git_installs', 'app_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('git_installs', 'app_slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('git_installs', 'html_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('git_installs', 'html_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('git_installs', 'app_slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('git_installs', 'app_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
