"""InstallationRecord model changed a few Ids to UUID from a type error and made all of them Optional with defaults

Revision ID: c9944d09f49c
Revises: e03d0fe4aa48
Create Date: 2025-10-13 20:19:42.413797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9944d09f49c'
down_revision: Union[str, Sequence[str], None] = 'e03d0fe4aa48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('github_installation_records', 'app_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('github_installation_records', 'app_slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('github_installation_records', 'access_tokens_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('github_installation_records', 'html_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('github_installation_records', 'repositories_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('github_installation_records', 'installation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('github_installation_records', 'installation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('github_installation_records', 'repositories_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('github_installation_records', 'html_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('github_installation_records', 'access_tokens_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('github_installation_records', 'app_slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('github_installation_records', 'app_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
